name: Github Release

on:
  workflow_dispatch:

  workflow_call:

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download *.cfe
        uses: actions/download-artifact@v2
        with:
          name: legendcity-cfe-archive
          path: build/

      - name: Display structure of downloaded files
        run: ls -R build/

      - name: GitHub Release creation
        uses: anton-yurchenko/git-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # UNRELEASED: "update"
        with:
          args: build/*.cfe
