name: Github Release

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Output artifact and cfe file name"
        default: "legendcity"
        required: true
        type: string

  workflow_call:
    inputs:
      name:
        description: "Output artifact and cfe file name"
        default: "legendcity"
        required: true
        type: string

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download *.cfe
        uses: actions/download-artifact@main
        with:
          name: ${{ inputs.name }}
          path: build/

      - name: GitHub Release creation
        uses: anton-yurchenko/git-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # UNRELEASED: "update"
        with:
          args: build/*.cfe
