name: Release

# git tag v0.0.0
# git push origin --tags
# git push --delete origin v0.0.0
# git tag --delete v0.0.0

on:
  push:
    # branches:
    #   - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    uses: legendcity/legendcity-1c/.github/workflows/build-cfe.yml@main

  release:
    needs: build
    uses: legendcity/legendcity-1c/.github/workflows/github-release.yml@main
